# This file was generated by GoReleaser. DO NOT EDIT.
cask "beans" do
  version "0.10.0"

  on_macos do
    on_arm do
      sha256 "9670959acfe454bf38d22dc678b6638651bc18acebb2c524d4de0e489bd1b2d4"
      url "https://github.com/xRiErOS/beans/releases/download/v#{version}/beans_Darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "70f8a72293106dba1abc5e936f01a216320ed80aaa9af83b3c34d1c8479d16e6"
      url "https://github.com/xRiErOS/beans/releases/download/v#{version}/beans_Darwin_x86_64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "eb682c126a7b46e7826fea2fe67367d2d203f40543b9b5442bfec8e9659f1575"
      url "https://github.com/xRiErOS/beans/releases/download/v#{version}/beans_Linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "c789b31cb0687cfce3d296d49803a989cd78dae6df3f224c02e6cd348061693b"
      url "https://github.com/xRiErOS/beans/releases/download/v#{version}/beans_Linux_x86_64.tar.gz"
    end
  end

  name "beans"
  desc "Agentic-first issue tracker (xRiErOS fork)"
  homepage "https://github.com/xRiErOS/beans"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "beans"
  binary "beans-serve"
  binary "beans-tui"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/beans"]
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/beans-serve"]
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/beans-tui"]
    end
  end

  # No zap stanza required
end
