# This file was generated by GoReleaser. DO NOT EDIT.
cask "beans" do
  version "0.8.0"

  on_macos do
    on_arm do
      sha256 "ed4d079ddb4a9a9be1313aa9a9031f417cc19738d7e27c62d33e1a37ae91b2be"
      url "https://github.com/xRiErOS/beans/releases/download/v#{version}/beans_Darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "35a6a0037bf21eabadbad27c813ca3e30c16148761aa9de3bde75cee3617ea9f"
      url "https://github.com/xRiErOS/beans/releases/download/v#{version}/beans_Darwin_x86_64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "0c2fa2c4fcf7304ce334e0f45ef6de0c45ab3f8b2db2452a44da69f7732c92e2"
      url "https://github.com/xRiErOS/beans/releases/download/v#{version}/beans_Linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "9c3d00dcb65688190acb1e7c658143e3babdbc8fd604d4575ecff7a38124084f"
      url "https://github.com/xRiErOS/beans/releases/download/v#{version}/beans_Linux_x86_64.tar.gz"
    end
  end

  name "beans"
  desc "Agentic-first issue tracker (xRiErOS fork)"
  homepage "https://github.com/xRiErOS/beans"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "beans"
  binary "beans-serve"
  binary "beans-tui"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/beans"]
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/beans-serve"]
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/beans-tui"]
    end
  end

  # No zap stanza required
end
