# This file was generated by GoReleaser. DO NOT EDIT.
cask "beans" do
  version "0.10.1"

  on_macos do
    on_arm do
      sha256 "ebe6835f4ed619c0a1c196e16e088adfc37ce3a0dbaf1dc09e6049c4b8a4158e"
      url "https://github.com/xRiErOS/beans/releases/download/v#{version}/beans_Darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "d3543b3192792f259701dfe990b60b2c28c49c3c479facbfb0e9718ecfcc5621"
      url "https://github.com/xRiErOS/beans/releases/download/v#{version}/beans_Darwin_x86_64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "db41ba5e4dd1672bf3e15ce39240e7d18661f9d28255eaabf17a1b92c1240aba"
      url "https://github.com/xRiErOS/beans/releases/download/v#{version}/beans_Linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "70ff255cc60cda48631f0dfef491ac40da8242f109affdfc4323b331a255a592"
      url "https://github.com/xRiErOS/beans/releases/download/v#{version}/beans_Linux_x86_64.tar.gz"
    end
  end

  name "beans"
  desc "Agentic-first issue tracker (xRiErOS fork)"
  homepage "https://github.com/xRiErOS/beans"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "beans"
  binary "beans-serve"
  binary "beans-tui"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/beans"]
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/beans-serve"]
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/beans-tui"]
    end
  end

  # No zap stanza required
end
